Rudeg/react-input-calendar

- README.md
- src/Calendar.js
- src/DaysView.js
- src/MonthsView.js
Previously, if the text field was empty (for example if you backspaced the text away), then immediately selected the calendar picker button, clicking the forward / backward buttons would cause a null exception.  Also, passing a null date into the component would show today's date in the text box.  Now null date is an ok thing to pass, and we just create a date to pass into the calendar pieces if we need to.
Added support for placeholder text in the input box, great if you want to start out with an empty date (maybe to display a format suggestion, or an action word).
Added missing propTypes to top of main component.
Fall back to js date parsing if strict moment parsing fails.  This makes the input box much more likely to figure out what date the user typed, even if it didn't match the …
> Better support null date, add placeholder, better parsing

- package.json
Bundle fails without `envify`, needs to be dependency to ensure installation.
> change envify to be dependency (not just devDep)

- dist/Calendar.js
- dist/DaysView.js
- dist/MonthsView.js
- src/Calendar.js
Fixes issue: #12 
Date was null so when it tried to go up to view the year it did not know what the year was which caused an error.
It now continues to use the date set in the initial state if no date is passed in (now).
> datePicker usable while date is blank

- dist/Calendar.js
- dist/DaysView.js
- dist/MonthsView.js
- dist/YearsView.js
- package.json
- src/Calendar.js
- src/DaysView.js
- src/MonthsView.js
- src/YearsView.js
`Warning: React.addons.classSet will be deprecated in a future version. See http://fb.me/react-addons-classset`
Make use of standalone package from [JedWatson/classnames](https://github.com/JedWatson/classnames) instead of React.addons.classSet
> Fix React warning about React.addons.classSet

- dist/Calendar.js
- src/Calendar.js
After looking closer at #23, I see there was a bug introduced.
``` js
onClick: this.props.openOnInputFocus ? this.toggleClick : '',
onFocus: this.props.openOnInputFocus ? this.toggleClick : '',
```
The issue comes from the fact that `onClick` calls `this.toggleClick` which in turn causes `onFocus` to be called. This then results in `this.toggleClick` being called a second time. The calendar will open and close with a single click.
It would be better to only use `onFocus` since `onClick` is redundant.
> Only use onFocus when openOnInputFocus option is set

- dist/Calendar.js
- dist/DaysView.js
- dist/MonthsView.js
- dist/YearsView.js
- src/Calendar.js
- src/DaysView.js
- src/MonthsView.js
- src/YearsView.js
- styles/input-calendar.css
Some things to note:
- Min and max dates are both optional and any previous or later dates will become grayed out / deactivated (including the today button if it is outside of the selectable range)
- I added a clone() onto some of the date manipulations as moment dates are mutable and thus we should clone them if we may potentially not want the actual selected date to change sometimes when navigating around between months or years
- Trying to navigate past the min or max dates will set the selected date to the min or max possible if necessary
Let me know what you think and if there are any changes or additions you'd like :)
> Allow selection to be limited within a date range

- dist/Calendar.js
- src/Calendar.js
In the presense of ~25 calendar components, any click on the document triggers `.render` call on every one of them. This takes ~35ms on my laptop. 
With this check, no needless work is being done.
> Prevent calling setState on isVisible if it hasn't changed

- dist/Calendar.js
- dist/DaysView.js
Weekdays in germany start usually with monday.
- if the 'day' function is used in DaysView.js it is not locale aware.
- translation for "Today" to german.
> Support german weekdays and today button

- dist/Calendar.js
- dist/DaysView.js
after the pull request https://github.com/Rudeg/react-input-calendar/pull/35 deleted my changes accidentally, here is a new pull request for a german date format and german date button.
the same changes as in https://github.com/Rudeg/react-input-calendar/pull/34
> Support german weekdays and today button (again)

- dist/Calendar.js
- dist/Cell.js
- dist/DaysView.js
- src/Calendar.js
- src/Cell.js
- src/DaysView.js
In current react props can no longer be just changed. This broke the calendar view as the `cell` class was never applied. This pull request fixes this issue.
I also updated the `src` files to include the german translation additions. It was missing there so running `gulp` to generate `dist` files created wrong artifacts.
> No longer mutate props as they are frozen.

- styles/input-calendar.css
Commit f999f81340809c5552ae0bc5e4849f4b4afbbe8d changed a css selector and made it so that hovering over a selected date made the text the same color as the background.
This updates the :hover selector for the selected cell so that the text color is white.
> Fixes css specificity

- src/Calendar.js
- src/day-view.js
- src/month-view.js
- src/year-view.js
Compare minDate and maxDate with a precision of a day instead of milliseconds
See: http://momentjs.com/docs/#/query/
> Fix minDate and maxDate precision bug

- src/day-view.js
next() and prev() needs to be bound to DayView instance to prevent 'undefined' issues if minDate or maxDate is set.
> Bind next() and prev() to DayView instance

- README.md
- src/Calendar.js
If strictDateParsing is set, the parsing process will catch bad dates and does
not try to parse the date with the native js date function and does not set
the date to now either. Therefore the computed date will be reported as 'Invalid date'.
> Add prop to control date parsing

- README.md
- src/Calendar.js
Add prop parsingFormat to allow the parsing format to be different to the display format. The parsing does only happen if the date was entered manually and on blur gets called.
> Allow display format to be different to on blur parsing format

- README.md
- src/Calendar.js
With this prop, users will be able to easily translate 'today'.
Other locale features are handled by moment already.
Also, added `hideTouchKeyboard` prop to README.
> Add today text

- src/Calendar.js
React input calendar doesn't seem to hide when you leave the calendar field by tabbing away, only closes on click away. I thought this may help some of the other people with similar problem.
> Added a prop to hide calendar when on blur from the field happens

- src/day-view.js
- src/tests/get-days-titles-locale-test.js
The original getDaysTitles in DayView does not support any of the locales where a week starts on a monday (except for german because of the if-branch). The improved version works for all locales.
> Support getDaysTitles for all locales

- README.md
The `customIcon` prop was missing from the README and I had to look in the source file to find out about it. Hopefully, this will save other people some time.
> Update README with customIcon

- src/index.js
As of React v15.0 input values must be strings or undefined. Cannot use null anymore as we get a warning.
Warning: `value` prop on `input` should not be null. Consider using the empty string to clear the component or `undefined` for uncontrolled components.
> Use undefined for default input value

- src/index.js
A click issue is mentioned [here](https://github.com/Rudeg/react-input-calendar/pull/96) but I [(and others)](https://github.com/Rudeg/react-input-calendar/issues/100) feel this is too heavy-handed. 
In my case, this broke `<button type='submit'>` from functioning as a normal form submit button.
> This allows document clicks to proceed normally

- src/index.js
Fixes #91 and #97. #91 is already kind of fixed in `master`, but not when it's being used together with `closeOnSelect`.
I tested the following scenarios inside the storybook and they all work as documented:
`<Calendar format="DD/MM/YYYY" date="01/01/2016" />`
`<Calendar disabled={true} format="DD/MM/YYYY" date="01/01/2016" />`
`<Calendar disabled={false} format="DD/MM/YYYY" date="01/01/2016" />`
`<Calendar closeOnSelect={false} format="DD/MM/YYYY" date="01/01/2016" />`
`<Calendar closeOnSelect={true} format="DD/MM/YYYY" date="01/01/2016" />`
`<Calendar closeOnSelect={true} format="DD/MM/YYYY" date="01/01/2016" />`
`<Calendar closeOnSelect={true} disabled={true} format="DD/MM/YYYY" date="01/01/2016" />`
`<Calendar closeOnSelect={true} disabled={false} format="DD/MM/YYYY" date="01/01/2016" …
> Make closeOnSelect and month switch play nice together

- src/icon.js
When using the customIcon prop it throws a "cs is not defined error". Classnames import was missing.
> Fixed cs is not defined when using customIcon prop

- README.md
- src/day-view.js
- src/index.js
- src/stories/index.js
Added two new setting options:
1. displayYrWithMonth {boolean}: Allows the user to change the header on Day View from just month to month and year. Default is false.
2. defaultView {int} : lets the user set the view that they want the calendar to open in. Default is 0.
Notes: 
- if the user sets the minView but not defaultView, the currentView is defaulted to minView.
- if the user sets the minView higher than the defaultView, the currentView is default to minView.
- else the currentView is set to defaultView.
> Adds 2 new setting options; Resolves issue #122

- README.md
- src/index.js
Added 'onInputChange' to be triggered in Calendar's onChange handler (changeDate) to modify the value before it is set to state. 
This allows users to pass in a method to modify the input string before it is set. For example, the user can filter characters by length or values, auto-fill back slashes, and auto-correct.
> Add input change handler
